Make releases great again
Signed-off-by: Jonas Köhnen <jonas.koehnen@sap.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,46 +1,59 @@
-# Creates a GitHub Release.
-# Workflow is manually run.
-# Preselect branch or tag before running this workflow.
-name: release
+# Creates a GitHub release in draft state, including artifacts to be published.
+# Review artifacts and publish the draft release to trigger further release
+# workflows (release-images.yml, release-packages.yml). Preselect the correct
+# branch before running this workflow!
+
+name: Prepare release
 
 on:
   workflow_dispatch:
     inputs:
+      version:
+        description: Version to release, e.g., v2.0.0. Ignored if nightly is enabled.
+        required: false
+        type: string
       nightly:
-        description: "Mark as nightly build"
+        description: Is this a nightly release?
         required: true
-        default: true
-        type: boolean
-      dogorelease:
-        description: "Run goreleaser"
-        required: true
-        default: true
+        default: false
         type: boolean
 
 permissions:
-  contents: write
-  id-token: write
-  packages: write
+  contents: read
 
 jobs:
-  build-ui-dist:
-    runs-on: ubuntu-latest
+  setup:
+    name: Setup
+    runs-on: ubuntu-slim
+    permissions:
+      contents: write
     outputs:
-      version: ${{ steps.make-distribution-tarball.outputs.version }}
+      version: ${{ steps.version.outputs.version }}
     steps:
+      - name: Refuse nightly release on main repository
+        if: github.repository == 'openbao/openbao' && inputs.nightly
+        run: echo '::error::Refusing to run nightly release on main repo' && exit 1
+
+      - name: Refuse regular release on nightly repository
+        if: github.repository == 'openbao/openbao-nightly' && !inputs.nightly
+        run: echo '::error::Refusing to run regular release on nightly repo' && exit 1
+
       - name: Checkout
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
-          fetch-depth: 0 # Required by GoRelease
+          fetch-tags: true
 
-      - name: Configure nightly build
-        if: inputs.nightly
+      - name: Determine version
+        id: version
         run: |
-          # Locally remove previous nightly tags so they do not interfere
-          # with nightly tag computation. Also add the upstream.
+          if [[ "$NIGHTLY_RELEASE" == 'false' ]]; then
+            echo "version=${VERSION}" >> "$GITHUB_OUTPUT" && exit
+          fi
+
+          # Locally remove previous nightly tags so they do not interfere with
+          # nightly tag computation. Also add the upstream.
           git remote add upstream https://github.com/openbao/openbao
           git fetch --all
-
           for tag in $(git tag); do
             if [[ "$tag" == *nightly* ]]; then
               echo "Deleting $tag"
@@ -48,150 +61,286 @@ jobs:
             fi
           done
 
-          # Then create a nightly tag for this commit. Because this uses the
-          # time of commit, it is stable across different runners.
-          nightly_tag="$(bash ./scripts/nightly_tag.sh)"
-          git tag "$nightly_tag"
+          # Then generate a nightly tag for this commit.
+          echo "version=$(./scripts/nightly_tag.sh)" >> "$GITHUB_OUTPUT"
+        env:
+          VERSION: ${{ inputs.version }}
+          NIGHTLY_RELEASE: ${{ inputs.nightly }}
 
-      - name: Node setup
+      - name: Refuse versions that do not start with 'v'
+        if: "!startsWith(steps.version.outputs.version, 'v')"
+        run: echo "::error::Version '$VERSION' must start with a 'v'" && exit 1
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+
+      # Avoid creating the initial release resource via GoReleaser to stop
+      # parallel runs from racing against each other and creating multiple
+      # releases.
+      - name: Create draft release
+        run: |
+          gh release create "$VERSION" \
+            --draft \
+            --repo="$GITHUB_REPOSITORY" \
+            --title="$VERSION" \
+            --target="$GITHUB_SHA" \
+            --prerelease="$PRERELEASE"
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+          PRERELEASE: ${{ inputs.nightly || contains(steps.version.outputs.version, '-') }}
+          GH_TOKEN: ${{ github.token }}
+
+      - name: Upload GPG signing key
+        if: github.repository == 'openbao/openbao'
+        run: gh release upload "$VERSION" website/public/assets/openbao-gpg-pub-20240618.asc
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+          GH_TOKEN: ${{ github.token }}
+
+  build-ui:
+    name: Build UI
+    runs-on: ubuntu-latest
+    needs:
+      - setup
+    steps:
+      - name: Checkout
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+
+      - name: Set up Node
         uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
         with:
           node-version-file: ui/package.json
 
-      - name: PNPM setup
+      - name: Set up PNPM
         uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
         with:
           package_json_file: ui/package.json
 
-      - name: UI Cache Setup
+      - name: Set up UI cache
         uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
         with:
-          path: |
-            http/web_ui/
+          path: http/web_ui/
           key: ${{ github.ref }}-ui
 
       - name: Build UI
-        id: ui-build
         run: make static-dist
 
-  release-main:
+  build:
+    name: Build ${{ matrix.target.os }}/${{ matrix.target.arch }}
     runs-on: ubuntu-latest
     needs:
-      - build-ui-dist
+      - setup
+      - build-ui
+    permissions:
+      contents: write
+      id-token: write
     env:
-      DOCKER_CLI_EXPERIMENTAL: "enabled"
       SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES: "true"
       SYFT_GOLANG_SEARCH_REMOTE_LICENSES: "true"
     strategy:
+      fail-fast: false
       matrix:
-        release_os:
-          - linux
-          - hsm
-          - darwin
-          - freebsd
-          - netbsd
-          - openbsd
-          - windows
+        target:
+          - { os: linux,   arch: amd64       }
+          - { os: linux,   arch: arm, arm: 6 }
+          - { os: linux,   arch: arm64       }
+          - { os: linux,   arch: ppc64le     }
+          - { os: linux,   arch: riscv64     }
+          - { os: linux,   arch: s390x       }
+          - { os: hsm,     arch: amd64       }
+          - { os: hsm,     arch: arm64       }
+          - { os: darwin,  arch: amd64       }
+          - { os: darwin,  arch: arm64       }
+          - { os: freebsd, arch: amd64       }
+          - { os: freebsd, arch: arm64       }
+          - { os: freebsd, arch: arm, arm: 6 }
+          - { os: netbsd,  arch: amd64       }
+          - { os: netbsd,  arch: arm64       }
+          - { os: netbsd,  arch: arm, arm: 6 }
+          - { os: openbsd, arch: amd64       }
+          - { os: openbsd, arch: arm64       }
+          - { os: openbsd, arch: arm, arm: 6 }
+          - { os: windows, arch: amd64       }
+          - { os: windows, arch: arm64       }
+
     steps:
-      - name: Free additional storage on runner
-        if: inputs.dogorelease
-        run: |
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
-
-      - name: Check free storage on runner
-        if: inputs.dogorelease
-        run: |
-          df -h .
-
       - name: Checkout
-        if: inputs.dogorelease
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
-          fetch-depth: 0 # Required by GoRelease
+          fetch-depth: 0 # Required by GoReleaser.
 
-      - name: Configure nightly build
-        if: inputs.dogorelease && inputs.nightly
-        run: |
-          # Locally remove previous nightly tags so they do not interfere
-          # with nightly tag computation. Also add the upstream.
-          git remote add upstream https://github.com/openbao/openbao
-          git fetch --all
-
-          for tag in $(git tag); do
-            if [[ "$tag" == *nightly* ]]; then
-              echo "Deleting $tag"
-              git tag --delete "$tag"
-            fi
-          done
-
-          # Then create a nightly tag for this commit. Because this uses the
-          # time of commit, it is stable across different runners.
-          nightly_tag="$(bash ./scripts/nightly_tag.sh)"
-          git tag "$nightly_tag"
-
-      - name: Golang Setup
-        if: inputs.dogorelease
+      - name: Set up Go
         uses: ./.github/actions/set-up-go
 
-      - name: go-check
-        if: inputs.dogorelease
-        run: go version
-
-      - name: UI Cache Setup
-        if: inputs.dogorelease
+      - name: Set up UI cache
         uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
         with:
-          path: |
-            http/web_ui/
+          path: http/web_ui/
           key: ${{ github.ref }}-ui
 
-      # Supports syft/sbom generation
-      - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
-        if: inputs.dogorelease
+      - name: Install Syft
+        uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
 
-        # Supports Buildx
-      - name: Qemu Setup
-        if: inputs.dogorelease
-        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
-
-      - name: Buildx Setup
-        if: inputs.dogorelease
-        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
-
-      - name: Cosign Install
-        if: inputs.dogorelease
+      - name: Install Cosign
         uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
 
-      - name: "Docker Login: ghcr.io"
-        if: inputs.dogorelease && (startsWith(github.ref, 'refs/tags/') || inputs.nightly)
-        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Install GoReleaser
-        if: inputs.dogorelease && (startsWith(github.ref, 'refs/tags/') || inputs.nightly)
         uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
         with:
           install-only: true
-          # TODO: remove version pinning when Goreleaser 2.8 is released
-          version: v2.5.1
+          version: v2.16.0
+
+      - name: Import GPG key
+        id: gpg-import
+        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSWORD }}
+
+      # This is required for GoReleaser's 'nfpms' stage.
+      - name: Save GPG key to disk
+        run: |
+          GPG_KEY_FILE=$(mktemp)
+          echo "$GPG_PRIVATE_KEY" > "$GPG_KEY_FILE"
+          echo "GPG_KEY_FILE=${GPG_KEY_FILE}" >> "$GITHUB_ENV"
+        env:
+          GPG_TTY: /dev/ttys000 # Set the GPG_TTY to avoid issues with pinentry.
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
 
       - name: Install C compiler for arm64 CGO cross-compilation
-        if: inputs.dogorelease && matrix.release_os == 'hsm'
+        if: matrix.target.os == 'hsm' && matrix.target.arch == 'arm64'
         run: sudo apt install -y gcc-aarch64-linux-gnu
 
-      - name: "GoReleaser: Release"
-        if: inputs.dogorelease && (startsWith(github.ref, 'refs/tags/') || inputs.nightly)
+      - name: Run GoReleaser
         run: |
-          if [[ ! -f "goreleaser.${{ matrix.release_os }}.yaml" ]]; then
-            yq e '.builds[0].goos |= ["${{ matrix.release_os }}"] | .checksum.name_template |= "checksums-${{ matrix.release_os }}.txt"' "goreleaser.other.yaml" | goreleaser release --clean --timeout=60m --verbose --parallelism 2 -f -
-          else
-            goreleaser release --clean --timeout=60m --verbose --parallelism 2 -f "goreleaser.${{ matrix.release_os }}.yaml"
+          # Pick the right file:
+          file='goreleaser.${{ matrix.target.os }}.yaml'
+          [[ ! -f "$file" ]] && file=goreleaser.other.yaml
+
+          # Inject 'goos' and 'goarch':
+          query='
+              .builds[0].goos   |= ["${{ case(matrix.target.os == 'hsm', 'linux', matrix.target.os) }}"]
+            | .builds[0].goarch |= ["${{ matrix.target.arch }}"]
+          '
+
+          # Inject 'goarm' if defined:
+          if [[ ! -z '${{ matrix.target.arm }}' ]]; then
+            query="$query"' | .builds[0].goarm |= ["${{ matrix.target.arm }}"]'
           fi
+
+          # Create the tag locally so goreleaser knows what to target:
+          git tag "$VERSION"
+
+          # Ship it:
+          yq eval "$query" "$file" | goreleaser release --clean --verbose --timeout=30m -f -
         env:
+          VERSION: ${{ needs.setup.outputs.version }}
           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
           COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GPG_FINGERPRINT: ${{ steps.gpg-import.outputs.fingerprint }}
+          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          NFPM_DEFAULT_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
           NIGHTLY_RELEASE: ${{ inputs.nightly }}
+
+      - name: Remove GPG key from disk
+        if: always()
+        run: rm -f "$GPG_KEY_FILE"
+
+  build-dist:
+    name: Build distribution source tarball
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    needs:
+      - setup
+      - build-ui
+    steps:
+      - name: Checkout
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+
+      - name: Set up Go
+        uses: ./.github/actions/set-up-go
+
+      - name: Set up Node
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
+        with:
+          node-version-file: ui/package.json
+
+      - name: Set up PNPM
+        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
+        with:
+          package_json_file: ui/package.json
+
+      - name: Make LICENSE_NODE_MODULES.txt
+        run: |
+          pnpm install
+          pnpx generate-license-file --input package.json --output ../LICENSE_NODE_MODULES.txt
+        working-directory: ui
+
+      - name: Make SPDX_NODE_MODULES.txt
+        run: |
+          jq -r .license ui/node_modules/*/package.json | \
+            grep -v url | \
+            sed 's/.*"type": "//;s/",//' | \
+            grep -v { | grep -v } | grep -v ^null$ | \
+            awk '{if ((($2 == "OR") || ($2 == "AND")) && (substr($1, 0, 1) != "(")) { print "(" $0 ")"} else {print $0}}' | \
+            sort -u > SPDX_NODE_MODULES.txt
+
+      - name: Make VERSION_NODE_MODULES.txt
+        run: jq -r '"\(.name) \(.version)"' ui/node_modules/*/package.json > VERSION_NODE_MODULES.txt
+
+      - name: Make LICENSE_DEPENDENCIES.md
+        run: |
+          go run github.com/google/go-licenses@v1.6.0 report ./... \
+            --ignore github.com/openbao/openbao \
+            --template LICENSE_DEPENDENCIES.tpl \
+            > LICENSE_DEPENDENCIES.md
+
+      - name: Vendor Go modules
+        run: go mod vendor
+
+      - name: Make distribution source tarball
+        run: |
+          tar --exclude .git --exclude '*.gz' --exclude node_modules --exclude .pnpm-store -cJf ../openbao-dist-$VERSION.tar.xz --xform="s,^\.,openbao-dist-$VERSION," .
+          mv ../*.xz .
+        env:
+          VERSION: ${{ needs.setup.outputs.version }}
+
+      - name: Upload distribution source tarball
+        run: gh release upload "$VERSION" *.xz
+        env:
+          VERSION: ${{ needs.setup.outputs.version }}
+          GITHUB_TOKEN: ${{ github.token }}
+
+  publish-nightly:
+    name: Auto-publish nightly release
+    if: inputs.nightly
+    runs-on: ubuntu-slim
+    needs:
+      - setup
+      - build
+      - build-dist
+    permissions:
+      contents: write
+    steps:
+      - name: Publish release
+        run: gh release edit "$VERSION" --draft=false --repo "$GITHUB_REPOSITORY"
+        env:
+          VERSION: ${{ needs.setup.outputs.version }}
+          GITHUB_TOKEN: ${{ github.token }}
+
+  release-nightly-images:
+    name: Release container images
+    if: inputs.nightly
+    needs:
+      - setup
+      - publish-nightly
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+    uses: ./.github/workflows/release-images.yml
+    with:
+      version: ${{ needs.setup.outputs.version }}
+    secrets: inherit
